### ISSUE TITLE
add explanation on how to extract original boot logo from firmware

### ISSUE THREAD

**Issue by Sci3ntia** [friedkeenan/switch-logo-patcher#1]
I wanted to extract the original boot logo from my switch, however i can't for the life of me find the system title which contains the logo, could you make it more clear how to do so in the readme?

**Comment by friedkeenan** [comment]
Yeah I've been wanting to do this, it's just that the process is a little involved/complex. I think I'd prefer to write a script to do it

**Comment by Sci3ntia** [comment]
thanks, do you think you could point me in the right direction or does it require tools that don't exist yet?

**Comment by chronos-tcs** [comment]
No update, I've extracted all files from Switch firmware, but as noob I am in this, couldn't the file

**Comment by impeeza** [comment]
Hi, Any update on this?
