### ISSUE TITLE
not work on W10

### ISSUE THREAD

**Issue by chronoss09** [friedkeenan/switch-logo-patcher#11]
can u do something ?

**Comment by friedkeenan** [comment]
What specific issue are you getting? This should work perfectly fine on Windows 10. Post the error it's telling you

**Comment by chronoss09** [comment]
![Capture](https://user-images.githubusercontent.com/17669980/142786074-a12ecadc-4d2d-4ce3-8ac9-e34bb4d7a1d2.PNG)

**Comment by friedkeenan** [comment]
You need to specify `python`, e.g. `python gen_patches.py ...`

**Comment by chronoss09** [comment]
![Capture](https://user-images.githubusercontent.com/17669980/142786367-76d92cae-c0f3-427f-8690-2e98bef8da97.PNG)

**Comment by chronoss09** [comment]
?????? until today, nothing work :(

**Comment by THZoria** [comment]
> ?????? until today, nothing work :(

it's a problem of the python module and not of the script (python is really lazy on this point)
