### ISSUE TITLE
Firmware 14.0.0 support.

### ISSUE THREAD

**Issue by impeeza** [friedkeenan/switch-logo-patcher#13]
Hi I did update to firmware 14.0.0 but no generated files works on it.  Thanks.

**Comment by friedkeenan** [comment]
You're using the latest changes? #12 should have fixed this

**Comment by impeeza** [comment]
Yes I am using it, will make new set of test and let you to know.  Thanks.

**Comment by friedkeenan** [comment]
Closing this now, if you're still having issues on 14.0.0 feel free to comment on this issue
