### ISSUE TITLE
PIL error when running script

### ISSUE THREAD

**Issue by TheMemeSniper** [friedkeenan/switch-logo-patcher#14]
Traceback (most recent call last):
  File "C:\Users\fluff\Downloads\switch-logo-patcher-master\switch-logo-patcher-master\gen_patches.py", line 7, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

I have Pillow installed, as PIL isn't available anymore.

**Comment by friedkeenan** [comment]
You need to install the `Pillow` package, as listed in [requirements.txt](https://github.com/friedkeenan/switch-logo-patcher/blob/master/requirements.txt) which you could install with simply `pip install -r requirements.txt`.
