### ISSUE TITLE
FW 15 support

### ISSUE THREAD

**Issue by impeeza** [friedkeenan/switch-logo-patcher#15]
Hi, I don't know how to create a PR (hope learn soon)

for the FW 15 the additional values are `"7E9BB552AAEFF82363D1E8C97B5C6B95E3989E1A": 1704192,`  so the patch_info variable now should be:

```
patch_info = {
    # AM patches
    "C79F22F18169FCD3B3698A881394F6240385CDB1": 1668164,
    "01890C643E9D6E17B2CDA77A9749ECB9A4F676D6": 1962240,
    "C088ADC91417EBAE6ADBDF3E47946858CAFE1A82": 1962240,
    "3EC573CB22744A993DFE281701E9CBFE66C03ABD": 1716480,

    # Vi patches
    "7B4123290DE2A6F52DE4AB72BEA1A83D11214C71": 1831168,
    "723DF02F6955D903DF7134105A16D48F06012DB1": 1835264,
    "967F4C3DFC7B165E4F7981373EC1798ACA234A45": 1573120,
    "98446A07BC664573F1578F3745C928D05AB73349": 1589504,
    "0767302E1881700608344A3859BC57013150A375": 1593600,
    "7C5894688EDA24907BC9CE7013630F365B366E4A": 1593600,
    "7421EC6021AC73DD60A635BC2B3AD6FCAE2A6481": 1536256,
    "96529C3226BEE906EE651754C33FE3E24ECAE832": 1544448,
    "D689E9FAE7CAA4EC30B0CD9B419779F73ED3F88B": 1655040,
    "65A23B52FCF971400CAA4198656D73867D7F1F1D": 1655040,
    "B295D3A8F8ACF88CB0C5CE7C0488CC5511B9C389": 1696000,
    "82EE58BEAB54C1A9D4B3D9ED414E84E31502FAC6": 1708288,
    "AFEAACF3E88AB539574689D1458060657E81E088": 1716480,
    "7E9BB552AAEFF82363D1E8C97B5C6B95E3989E1A": 1704192,
}
```

**Comment by friedkeenan** [comment]
There are other ways to make pull requests, but for something this simple it's sufficient to just edit on github by clicking the pencil button here
![image](https://user-images.githubusercontent.com/20881398/195233730-08e76414-ef5f-4f3d-a1ee-64cd4bee8299.png)
and then making sure this checkbox is checked
![image](https://user-images.githubusercontent.com/20881398/195233810-ac442538-982b-4781-9571-343e0b412f13.png)

Thank you for the contribution all the same. Would like someone to verify this works before merging however.

**Comment by impeeza** [comment]
has been confirmed by third person on gbatemp:
https://gbatemp.net/threads/original-nintendo-logo-from-firmware-switch-logo-patcher.613041/post-9965763

**Comment by friedkeenan** [comment]
Alright I guess I'll just commit it myself

**Comment by impeeza** [comment]
Sorry, I don't know why the confirmations of this never come to me, and my mind just ignore your clear instructions about how to create a PR,  thanks again for taking your time, sorry if I was ungrateful and disrespect, I was only distracted, again sorry.

**Comment by friedkeenan** [comment]
Don't pay it any mind, I certainly didn't. No need to apologize
