### ISSUE TITLE
how do i specify the old boot logo?

### ISSUE THREAD

**Issue by Arusene-Arsene** [friedkeenan/switch-logo-patcher#18]

**Comment by friedkeenan** [comment]
You can specify the old logo using the `-o` flag, like so: `gen-patches.py -o original.png new_logo_patches new_logo.png`.

To obtain the old logo, there is [a guide on GBAtemp](https://gbatemp.net/threads/original-nintendo-logo-from-firmware-switch-logo-patcher.613041/).
