### ISSUE TITLE
 Explain the code comments, what AM Patches are, and what Vi Patches

### ISSUE THREAD

**Issue by Pugemon** [friedkeenan/switch-logo-patcher#20]
I understand that Vi Patches refer to OFW patches, but I still don't understand what AM Patches are.

**Comment by friedkeenan** [comment]
The patches for AM are applied to the [AM sysmodule](https://switchbrew.org/wiki/Applet_Manager_services), which are used for firmwares less than 4.0.0 or so I think, before the logo data was moved to the [Vi sysmodule](https://switchbrew.org/wiki/Display_services), which is what the Vi patches are applied to.

The comments are indeed poor, and I wish I had labeled them in correspondence with their firmware versions, but I don't think it's worth it enough for me to put in the work to go back and figure all that out again, or to verify someone else doing so on my behalf.

**Comment by Pugemon** [comment]
> The patches for AM are applied to the [AM sysmodule](https://switchbrew.org/wiki/Applet_Manager_services), which are used for firmwares less than 4.0.0 or so I think, before the logo data was moved to the [Vi sysmodule](https://switchbrew.org/wiki/Display_services), which is what the Vi patches are applied to.
> 
> The comments are indeed poor, and I wish I had labeled them in correspondence with their firmware versions, but I don't think it's worth it enough for me to put in the work to go back and figure all that out again, or to verify someone else doing so on my behalf.

Thank you for the explanations. Maybe you should separate the old code for "AM-VI "96529C3226BEE906EE651754C33FE3E24ECAE832": 1544448,    # FW 10.0.0" 
To old branch?

**Comment by friedkeenan** [comment]
Like I said, I would like the comments to be better in such a way, but I don't view it as worth the effort. The only maintenance this project needs is a new line for a new offset when the vi sysmodule gets updated.
