### ISSUE TITLE
Not working on FW 16.1.0

### ISSUE THREAD

**Issue by SASA-Tech** [friedkeenan/switch-logo-patcher#22]
Not working on FW 16.1.0 (AMS 1.5.5)

**Comment by friedkeenan** [comment]
That shouldn't be the case, as vi was not updated in 16.1.0. Please make sure you're using the correct patches and that they are placed in the correct place, i.e. the `.ips` files are in the `/atmosphere/exefs_patches/<any name>/` directory on your SD card.

**Comment by SASA-Tech** [comment]
They are in exactly that position but the original logo continues to appear

**Comment by friedkeenan** [comment]
May you please delete that folder on your SD card, delete the folder containing the patches on your PC, and then regenerate the patches and try again?

**Comment by SASA-Tech** [comment]
![Uploading image.jpg…]()

**Comment by SASA-Tech** [comment]
Ho rigenerato più volte la patch. Non so dove sto sbagliando

**Comment by SASA-Tech** [comment]
I regenerated the patch several times. I don't know where I'm wrong

**Comment by friedkeenan** [comment]
I had someone else confirm it works on 16.1.0, and unfortunately your image does not seem to be uploading, so I'm going to close this issue for now.
