### ISSUE TITLE
Compatibility Atmosphere 1.6.2 (FW 17.0.0)

### ISSUE THREAD

**Issue by SASA-Tech** [friedkeenan/switch-logo-patcher#23]
On atmosphere 1.6.2 (FW 17.0.0) the custom logo does not work

**Comment by friedkeenan** [comment]
Please make sure you're using the latest switch-logo-patcher (you may need to redownload it). Atmosphere version does not matter as long as it supports 17.0.0.

**Comment by friedkeenan** [comment]
Closing in lieu of any other information
