### ISSUE TITLE
Update for 11.0.1.

### ISSUE THREAD

**Issue by Skonikol** [friedkeenan/switch-logo-patcher#3]
Could you please make corrections for 11.0.1 Thank you very much.

**Comment by deejay87** [comment]
Hi, i can give you the firmware if you need friedkeenan

**Comment by Skonikol** [comment]
> Hi, i can give you the firmware if you need friedkeenan
do you have a link to the firmware 1101?

**Comment by deejay87** [comment]
i have

**Comment by Skonikol** [comment]
> i have

can you give it to me, please?
